[[redirects]]
    from = "/.well-known"
    to = "https://clipboardy.azurewebsites.net/apple-app-site-association"
    status = 200
    force = true
    [redirects.headers]
        Content-Type = "application/json"